const AddRoomStr = {
    area: "小区",
    area_placehold: "选择小区",
    landlord_placehold: "选择房东",
    base_info: "基本信息",
    types: [
        "类型",
        "住宅",
        "别墅",
        "商铺",
        "商住",
        "写字楼",
    ],
    huxing: "户型",
    shi: "室",
    ting: "厅",
    wei: "卫",
    mianji_louceng: "面积/楼层",
    pingmi: "平米",
    louceng: "楼层",
    chaoxiangs: [
        "朝向",
        "东",
        "南",
        "西",
        "北",
        "东南",
        "西南",
        "东北",
        "西北",
    ],
    zhuangxius: [
        "装修",
        "普通装修",
        "精装修",
        "豪华装修",
    ],
    danjia_zongjia: "单价/总价",
    yuan_pingmi: "元/平米",
    wanyuan: "万元",
    chewei_jiage: "车位/价格",
    chewei: "车位",
    wanyuan_ge: "万元/个",
    wuyegongsi: "物业公司",
    peitaosheshi: "设施配套",
    peitaosheshis: [
        [
            "电梯",
            "阳台",
            "宽带",
            "热水器",
            "电视",
        ],
        [
            "空调",
            "暖气",
            "冰箱",
            "洗衣机",
            "床",
        ],
        [
            "衣柜",
            "天然气",
        ],
    ],

};

export default AddRoomStr;