const AddRoomStr = {
    area: "小区",
    area_placehold: "选择小区",
    landlord_placehold: "选择房东",
    base_info: "基本信息",
    types: [
        "类型",
        "住宅",
        "别墅",
        "商铺",
        "商住",
        "写字楼",
    ],
    huxing: "户型",
    shi: "室",
    ting: "厅",
    wei: "卫",
    mianji_louceng: "面积/楼层",
    pingmi: "平米",
    louceng: "楼层",
    chaoxiangs: [
        "朝向",
        "东",
        "南",
        "西",
        "北",
        "东南",
        "西南",
        "东北",
        "西北",
    ],
    zhuangxius: [
        "装修",
        "普通装修",
        "精装修",
        "豪华装修",
    ],
    danjia_zongjia: "单价/总价",
    yuan_pingmi: "元/平米",
    wanyuan: "万元",
    chewei_jiage: "车位/价格",
    chewei: "车位",
    wanyuan_ge: "万元/个",
    wuyegongsi: "物业公司",
    wuyegongsi_ph: "请输入物业公司",
    peitaosheshi: "设施配套",
    peitaosheshis: [
        [
            { key: "elevator", value: "电梯" },
            { key: "balcony", value: "阳台" },
            { key: "broadband", value: "宽带" },
            { key: "hot_water_heater", value: "热水器" },
            { key: "tv", value: "电视" },
        ],
        [
            { key: "aircondition", value: "空调" },
            { key: "heating", value: "暖气" },
            { key: "refrigerator", value: "冰箱" },
            { key: "washing_machine", value: "洗衣机" },
            { key: "bed", value: "床" },
        ],
        [
            { key: "wardrobe", value: "衣柜" },
            { key: "gas", value: "天然气" },
        ],
    ],

};

export default AddRoomStr;