const CommonStr = {
    ch_title: "美腾房产",
    en_title: "MEI TENG",
    login: "登录",
    user: "账户",
    pass: "密码",
    ok: "确定",
    placeholder_user: "请输入您的账户名",
    placeholder_pass: "请输入您的密码",
    placeholder_serarch: "请输入关键词",
    remember_pass: "记住密码",
    default_sort: "默认排序",
    price_sort: "价格",
    date_sort: "时间",
    search_result_1: "共有",
    search_result_2: "个符合要求",
    fangdong: "房东",
    guke: "顾客",
    danjia: "单价",
    day: "天",
    xiaoshourenyuan: "销售人员",
    chushoushijian: "出售时间",
    lou: "楼",
};

export default CommonStr;