const CommonStr = {
    ch_title: "美腾房产",
    en_title: "MEI TENG",
    login: "登录",
    user: "账户",
    pass: "密码",
    ok: "确定",
    placeholder_user: "请输入您的账户名",
    placeholder_pass: "请输入您的密码",
    placeholder_serarch: "请输入关键词",
    remember_pass: "记住密码",
    search_result_1: "共有",
    search_result_2: "个符合要求",
    fangdong: "房东",
    guke: "顾客",
    danjia: "单价",
    day: "天",
    xiaoshourenyuan: "销售人员",
    chushoushijian: "出售时间",
    lou: "楼",
    sort_style: [
        "默认排序",
        "价格",
        "时间"
    ],
    sales_records: "例.售出房屋3套/租出房屋6套",
    others: "例.持有房地产经纪人证",
    add_landord: "添加房东",
    name: "姓名",
    sex: "性别",
    man: "男",
    woman: "女",
    age: "年龄",
    phone: "电话",
    id_card: "身份证号",
    remarks: "备注",
    native_place: "籍贯",
    add_customer: "添加顾客",
    add_area: "添加小区",
    area_name: "小区名字",
    area_address: "小区位置",
    area_around: "周边配套",
    area_trafic: "交通出行",
    area_label: "标签生成",
    add_staff: "添加员工",
};

export default CommonStr;